on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

env:
  AWS_REGION: ap-northeast-1
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GITHUB_NAME: github-actions[bot]

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get temporary credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{env.AWS_REGION}}

      - name: Cache Dependency
        uses: actions/cache@v3
        id: cache_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install CDK Dependency
        if: steps.cache_dependency_id.outputs.cache-hit != 'true'
        run: npm install

      - name: Synthesize CDK stacks
        run: npx cdk synth ${{ vars.STACK_NAME }} > cfn_git_sync/template.yaml

      - name: Assets publish
        run: npx cdk-assets publish -p cdk.out/${{ vars.STACK_NAME }}.assets.json

      - name: Add generated files to the pull request
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config --local user.email ${{ env.GITHUB_MAIL }}
          git config --local user.name ${{ env.GITHUB_NAME }}
          git add .
          git commit -m "Add generated template.yaml to the pull request"
          git push origin HEAD:${{ github.head_ref }}
